import random

import pandas as pd


zodiac_profiles = {
        "Aries": {
        "responsabilidad_disciplina_tareas_diarias": (6, 9),
        "preferencia_horario_estructurado": (3, 7),
        "adaptabilidad_cambios_variedad": (7, 10),
        "comodidad_situaciones_nuevas": (7, 10),
        "conexion_emocional_otros": (4, 7),
        "afectado_emociones_ajenas": (3, 6),
        "motivacion_grandes_metas_liderazgo": (8, 10),
        "iniciativa_proyectos_grupales": (8, 10),
        "creatividad_expresion_artistica": (5, 8),
        "placer_actividades_creativas": (5, 8),
        "importancia_estabilidad_seguridad": (5, 7),
        "incomodidad_incertidumbre_cambios": (4, 7),
        "compromiso_pasion_intensidad": (8, 10),
        "dificultad_indiferencia_desapasionada": (7, 10),
        "persona_optimista_lado_positivo": (7, 10),
        "entusiasmo_enfrentar_desafios": (8, 10),
        "valoracion_independencia_libertad": (7, 10),
        "preferencia_decisiones_propias": (7, 10),
        "detallista_precision_tareas": (4, 6),
        "perfeccionamiento_detalles_proyectos": (4, 6),
    },
    "Tauro": {
        "responsabilidad_disciplina_tareas_diarias": (7, 10),
        "preferencia_horario_estructurado": (6, 9),
        "adaptabilidad_cambios_variedad": (4, 7),
        "comodidad_situaciones_nuevas": (4, 7),
        "conexion_emocional_otros": (5, 8),
        "afectado_emociones_ajenas": (5, 8),
        "motivacion_grandes_metas_liderazgo": (5, 8),
        "iniciativa_proyectos_grupales": (5, 8),
        "creatividad_expresion_artistica": (4, 7),
        "placer_actividades_creativas": (4, 7),
        "importancia_estabilidad_seguridad": (8, 10),
        "incomodidad_incertidumbre_cambios": (7, 10),
        "compromiso_pasion_intensidad": (5, 8),
        "dificultad_indiferencia_desapasionada": (4, 7),
        "persona_optimista_lado_positivo": (5, 8),
        "entusiasmo_enfrentar_desafios": (4, 7),
        "valoracion_independencia_libertad": (5, 8),
        "preferencia_decisiones_propias": (5, 8),
        "detallista_precision_tareas": (7, 10),
        "perfeccionamiento_detalles_proyectos": (7, 10),
    },
    "Géminis": {
        "responsabilidad_disciplina_tareas_diarias": (4, 7),
        "preferencia_horario_estructurado": (3, 6),
        "adaptabilidad_cambios_variedad": (8, 10),
        "comodidad_situaciones_nuevas": (8, 10),
        "conexion_emocional_otros": (5, 8),
        "afectado_emociones_ajenas": (4, 7),
        "motivacion_grandes_metas_liderazgo": (5, 8),
        "iniciativa_proyectos_grupales": (6, 9),
        "creatividad_expresion_artistica": (7, 10),
        "placer_actividades_creativas": (7, 10),
        "importancia_estabilidad_seguridad": (4, 7),
        "incomodidad_incertidumbre_cambios": (4, 7),
        "compromiso_pasion_intensidad": (5, 8),
        "dificultad_indiferencia_desapasionada": (4, 7),
        "persona_optimista_lado_positivo": (7, 10),
        "entusiasmo_enfrentar_desafios": (7, 10),
        "valoracion_independencia_libertad": (6, 9),
        "preferencia_decisiones_propias": (6, 9),
        "detallista_precision_tareas": (4, 6),
        "perfeccionamiento_detalles_proyectos": (4, 6),
    },
    "Cáncer": {
        "responsabilidad_disciplina_tareas_diarias": (5, 8),
        "preferencia_horario_estructurado": (4, 7),
        "adaptabilidad_cambios_variedad": (5, 8),
        "comodidad_situaciones_nuevas": (5, 8),
        "conexion_emocional_otros": (8, 10),
        "afectado_emociones_ajenas": (8, 10),
        "motivacion_grandes_metas_liderazgo": (4, 7),
        "iniciativa_proyectos_grupales": (5, 8),
        "creatividad_expresion_artistica": (5, 8),
        "placer_actividades_creativas": (5, 8),
        "importancia_estabilidad_seguridad": (6, 9),
        "incomodidad_incertidumbre_cambios": (5, 8),
        "compromiso_pasion_intensidad": (5, 8),
        "dificultad_indiferencia_desapasionada": (4, 7),
        "persona_optimista_lado_positivo": (5, 8),
        "entusiasmo_enfrentar_desafios": (5, 8),
        "valoracion_independencia_libertad": (4, 7),
        "preferencia_decisiones_propias": (4, 7),
        "detallista_precision_tareas": (5, 8),
        "perfeccionamiento_detalles_proyectos": (5, 8),
    },
    "Leo": {
        "responsabilidad_disciplina_tareas_diarias": (6, 9),
        "preferencia_horario_estructurado": (5, 8),
        "adaptabilidad_cambios_variedad": (6, 9),
        "comodidad_situaciones_nuevas": (6, 9),
        "conexion_emocional_otros": (5, 8),
        "afectado_emociones_ajenas": (5, 8),
        "motivacion_grandes_metas_liderazgo": (8, 10),
        "iniciativa_proyectos_grupales": (8, 10),
        "creatividad_expresion_artistica": (7, 10),
        "placer_actividades_creativas": (7, 10),
        "importancia_estabilidad_seguridad": (5, 8),
        "incomodidad_incertidumbre_cambios": (5, 8),
        "compromiso_pasion_intensidad": (8, 10),
        "dificultad_indiferencia_desapasionada": (7, 10),
        "persona_optimista_lado_positivo": (7, 10),
        "entusiasmo_enfrentar_desafios": (8, 10),
        "valoracion_independencia_libertad": (6, 9),
        "preferencia_decisiones_propias": (6, 9),
        "detallista_precision_tareas": (5, 8),
        "perfeccionamiento_detalles_proyectos": (5, 8),
    },
    "Virgo": {
        "responsabilidad_disciplina_tareas_diarias": (7, 10),
        "preferencia_horario_estructurado": (6, 9),
        "adaptabilidad_cambios_variedad": (5, 8),
        "comodidad_situaciones_nuevas": (5, 8),
        "conexion_emocional_otros": (5, 8),
        "afectado_emociones_ajenas": (5, 8),
        "motivacion_grandes_metas_liderazgo": (5, 8),
        "iniciativa_proyectos_grupales": (5, 8),
        "creatividad_expresion_artistica": (4, 7),
        "placer_actividades_creativas": (4, 7),
        "importancia_estabilidad_seguridad": (6, 9),
        "incomodidad_incertidumbre_cambios": (5, 8),
        "compromiso_pasion_intensidad": (5, 8),
        "dificultad_indiferencia_desapasionada": (6, 9),
        "persona_optimista_lado_positivo": (5, 8),
        "entusiasmo_enfrentar_desafios": (5, 8),
        "valoracion_independencia_libertad": (5, 8),
        "preferencia_decisiones_propias": (5, 8),
        "detallista_precision_tareas": (8, 10),
        "perfeccionamiento_detalles_proyectos": (8, 10),
    },
    "Libra": {
        "responsabilidad_disciplina_tareas_diarias": (5, 8),
        "preferencia_horario_estructurado": (4, 7),
        "adaptabilidad_cambios_variedad": (7, 10),
        "comodidad_situaciones_nuevas": (7, 10),
        "conexion_emocional_otros": (6, 9),
        "afectado_emociones_ajenas": (6, 9),
        "motivacion_grandes_metas_liderazgo": (5, 8),
        "iniciativa_proyectos_grupales": (6, 9),
        "creatividad_expresion_artistica": (8, 10),
        "placer_actividades_creativas": (8, 10),
        "importancia_estabilidad_seguridad": (4, 7),
        "incomodidad_incertidumbre_cambios": (4, 7),
        "compromiso_pasion_intensidad": (6, 9),
        "dificultad_indiferencia_desapasionada": (4, 7),
        "persona_optimista_lado_positivo": (6, 9),
        "entusiasmo_enfrentar_desafios": (6, 9),
        "valoracion_independencia_libertad": (6, 9),
        "preferencia_decisiones_propias": (6, 9),
        "detallista_precision_tareas": (5, 7),
        "perfeccionamiento_detalles_proyectos": (5, 7),
    },
    "Escorpio": {
        "responsabilidad_disciplina_tareas_diarias": (6, 9),
        "preferencia_horario_estructurado": (5, 8),
        "adaptabilidad_cambios_variedad": (5, 8),
        "comodidad_situaciones_nuevas": (5, 8),
        "conexion_emocional_otros": (7, 10),
        "afectado_emociones_ajenas": (7, 10),
        "motivacion_grandes_metas_liderazgo": (7, 10),
        "iniciativa_proyectos_grupales": (6, 9),
        "creatividad_expresion_artistica": (5, 8),
        "placer_actividades_creativas": (5, 8),
        "importancia_estabilidad_seguridad": (6, 9),
        "incomodidad_incertidumbre_cambios": (5, 8),
        "compromiso_pasion_intensidad": (8, 10),
        "dificultad_indiferencia_desapasionada": (5, 8),
        "persona_optimista_lado_positivo": (5, 8),
        "entusiasmo_enfrentar_desafios": (7, 10),
        "valoracion_independencia_libertad": (5, 8),
        "preferencia_decisiones_propias": (5, 8),
        "detallista_precision_tareas": (5, 8),
        "perfeccionamiento_detalles_proyectos": (5, 8),
    },
    "Sagitario": {
        "responsabilidad_disciplina_tareas_diarias": (4, 7),
        "preferencia_horario_estructurado": (3, 6),
        "adaptabilidad_cambios_variedad": (8, 10),
        "comodidad_situaciones_nuevas": (8, 10),
        "conexion_emocional_otros": (5, 8),
        "afectado_emociones_ajenas": (4, 7),
        "motivacion_grandes_metas_liderazgo": (6, 9),
        "iniciativa_proyectos_grupales": (6, 9),
        "creatividad_expresion_artistica": (6, 9),
        "placer_actividades_creativas": (6, 9),
        "importancia_estabilidad_seguridad": (4, 7),
        "incomodidad_incertidumbre_cambios": (4, 7),
        "compromiso_pasion_intensidad": (6, 9),
        "dificultad_indiferencia_desapasionada": (4, 7),
        "persona_optimista_lado_positivo": (7, 10),
        "entusiasmo_enfrentar_desafios": (7, 10),
        "valoracion_independencia_libertad": (8, 10),
        "preferencia_decisiones_propias": (7, 10),
        "detallista_precision_tareas": (4, 6),
        "perfeccionamiento_detalles_proyectos": (4, 6),
    },
    "Capricornio": {
        "responsabilidad_disciplina_tareas_diarias": (8, 10),
        "preferencia_horario_estructurado": (7, 10),
        "adaptabilidad_cambios_variedad": (4, 7),
        "comodidad_situaciones_nuevas": (4, 7),
        "conexion_emocional_otros": (5, 8),
        "afectado_emociones_ajenas": (4, 7),
        "motivacion_grandes_metas_liderazgo": (7, 10),
        "iniciativa_proyectos_grupales": (7, 10),
        "creatividad_expresion_artistica": (4, 7),
        "placer_actividades_creativas": (4, 7),
        "importancia_estabilidad_seguridad": (8, 10),
        "incomodidad_incertidumbre_cambios": (6, 9),
        "compromiso_pasion_intensidad": (7, 10),
        "dificultad_indiferencia_desapasionada": (4, 7),
        "persona_optimista_lado_positivo": (5, 8),
        "entusiasmo_enfrentar_desafios": (6, 9),
        "valoracion_independencia_libertad": (5, 8),
        "preferencia_decisiones_propias": (5, 8),
        "detallista_precision_tareas": (8, 10),
        "perfeccionamiento_detalles_proyectos": (8, 10),
    },
    "Acuario": {
        "responsabilidad_disciplina_tareas_diarias": (5, 8),
        "preferencia_horario_estructurado": (4, 7),
        "adaptabilidad_cambios_variedad": (8, 10),
        "comodidad_situaciones_nuevas": (8, 10),
        "conexion_emocional_otros": (5, 8),
        "afectado_emociones_ajenas": (4, 7),
        "motivacion_grandes_metas_liderazgo": (6, 9),
        "iniciativa_proyectos_grupales": (6, 9),
        "creatividad_expresion_artistica": (8, 10),
        "placer_actividades_creativas": (8, 10),
        "importancia_estabilidad_seguridad": (4, 7),
        "incomodidad_incertidumbre_cambios": (4, 7),
        "compromiso_pasion_intensidad": (6, 9),
        "dificultad_indiferencia_desapasionada": (4, 7),
        "persona_optimista_lado_positivo": (6, 9),
        "entusiasmo_enfrentar_desafios": (6, 9),
        "valoracion_independencia_libertad": (8, 10),
        "preferencia_decisiones_propias": (8, 10),
        "detallista_precision_tareas": (4, 7),
        "perfeccionamiento_detalles_proyectos": (4, 7),
    },
    "Piscis": {
        "responsabilidad_disciplina_tareas_diarias": (5, 8),
        "preferencia_horario_estructurado": (4, 7),
        "adaptabilidad_cambios_variedad": (7, 10),
        "comodidad_situaciones_nuevas": (7, 10),
        "conexion_emocional_otros": (8, 10),
        "afectado_emociones_ajenas": (8, 10),
        "motivacion_grandes_metas_liderazgo": (5, 8),
        "iniciativa_proyectos_grupales": (5, 8),
        "creatividad_expresion_artistica": (8, 10),
        "placer_actividades_creativas": (8, 10),
        "importancia_estabilidad_seguridad": (4, 7),
        "incomodidad_incertidumbre_cambios": (5, 8),
        "compromiso_pasion_intensidad": (6, 9),
        "dificultad_indiferencia_desapasionada": (5, 8),
        "persona_optimista_lado_positivo": (6, 9),
        "entusiasmo_enfrentar_desafios": (6, 9),
        "valoracion_independencia_libertad": (5, 8),
        "preferencia_decisiones_propias": (5, 8),
        "detallista_precision_tareas": (5, 8),
        "perfeccionamiento_detalles_proyectos": (5, 8),
    }
}

# Generar datos aleatorios
def generate_random_data(zodiac_sign, age, gender):
    profile = zodiac_profiles[zodiac_sign]
    data = {
        "zodiac_sign": zodiac_sign,
        "age": age,
        "gender": gender,
    }
    for key, value in profile.items():
        data[key] = random.randint(value[0], value[1])
    return data

# Generar un conjunto de datos
num_samples = 1000  # Número de muestras a generar
zodiac_signs = list(zodiac_profiles.keys())
genders = ["Masculino", "Femenino"]

data = []
for _ in range(num_samples):
    zodiac_sign = random.choice(zodiac_signs)
    age = random.randint(18, 60)
    gender = random.choice(genders)
    sample = generate_random_data(zodiac_sign, age, gender)
    data.append(sample)

# Guardar los datos en un archivo CSV
df = pd.DataFrame(data)
df.to_csv("zodiac_sign_data.csv", index=False)

print("Datos generados y guardados en 'zodiac_sign_data.csv'")